apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarvis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jarvis
  template:
    metadata:
      labels:
        app: jarvis
    spec:
      containers:
        - name: jarvis
          image: sankettambe/jarvis-ai:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: jarvis-secrets
